# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  otel-collector-image:
    default: "ubuntu/opentelemetry-collector:0.120.0-24.04_stable"
    type: string
    description: Image to use by the otel collector Deployment.
