name: CI

# cancel all previous jobs in the same branch if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - main
    - track/**

jobs:
  quality-checks:
    name: Quality Checks
    strategy:
      matrix:
        charm:
          - knative-eventing
          - knative-operator
          - knative-serving
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@beta-craft
    with:
      charm-path: ./charms/${{ matrix.charm }}

  unit-tests:
    name: Unit Tests
    strategy:
      matrix:
        charm:
          - knative-eventing
          - knative-operator
          - knative-serving
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_unit-tests.yaml@beta-craft
    secrets: inherit
    with:
      charm-name: ${{ matrix.charm }}

# todo uncomment when integration tests are added
#  individual-integration-tests:
#    name: Individual Integration Tests
#    needs: [quality-checks, unit-tests]
#    strategy:
#      matrix:
#        charm:
#          - knative-eventing
#          - knative-operator
#          - knative-serving
#    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_integration-tests.yaml@beta-craft
#    secrets: inherit
#    with:
#      charm-name: ${{ matrix.charm }}

  bundle-tests:
    name: Bundle Tests
    needs: [quality-checks, unit-tests]
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_bundle.yaml@beta-craft

  observability-tests:
    name: Observability Tests
    needs: [quality-checks, unit-tests]
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_observability.yaml@beta-craft

  publish-on-success:
    # publish on push to main or track/** only if all tests pass
    name: Publish on Success
    if: github.event_name == 'push'
    # todo add individual-integration-tests when added
    needs: [quality-checks, unit-tests, bundle-tests, observability-tests]
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_publish.yaml@beta-craft
    secrets: inherit

  publish:
    # publish on PR if unittests and quality checks pass
    name: Publish
    needs: [quality-checks, unit-tests]
    if: github.event_name == 'pull_request'
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_publish.yaml@beta-craft
    secrets: inherit
